### ISSUE TITLE
Uploaded pdf cannot be read

### ISSUE THREAD

**Issue by etxbct** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#166]
After uploading fully functional pdf when opening on my computer gives error when clicking on them.

Pdf I have uploaded:
![image](https://user-images.githubusercontent.com/22001932/198044778-9d738a34-0b26-47c2-ace3-30a5833bba25.png)

Get this error when clicking on it:
![image](https://user-images.githubusercontent.com/22001932/198044640-9662893a-4a55-4435-ba5b-a7c9cad05faf.png)

Opening on my computer:
![image](https://user-images.githubusercontent.com/22001932/198045006-ea93bf7f-9372-4f20-bc60-c3aa1d14c76f.png)

**Comment by fjallemark** [comment]
The error was caused by incomplete upload of files. Not all files are affected, but the files that cannot be opened after download, has to be uploaded again.
Fixed in release 1.7.12.

**Comment by etxbct** [comment]
Hi,
tried today and still get error when I open it in a browser or in acrobat reader.
The file contain two streams and after the last stream the original file has some readable characters, but the file downloaded has lot off NULL at the end of last stream
I have open both files in Notepad++ and compared them.

Uploaded file:
[Bf Bilbo normal.pdf](https://github.com/tellurianinteractive/Tellurian.Trains.ModulesRegistryApp/files/10122633/Bf.Bilbo.normal.pdf)

Down loaded file:
[Bilbo.pdf](https://github.com/tellurianinteractive/Tellurian.Trains.ModulesRegistryApp/files/10122636/Bilbo.pdf)

**Comment by etxbct** [comment]
the difference of the two files
![image](https://user-images.githubusercontent.com/22001932/204785097-3fdbecb0-191b-4502-a2ea-f94a9508ddc0.png)
